
import { Button, HorizontalBox, ScrollView } from "std-widgets.slint";


export component MyApp inherits Window {
    // no-frame: true;
    background: #2d2d2d;
    default-font-size: 20px;
    preferred-width: 1200phx;
    preferred-height: 600phx;
    width: 1200phx;
    height: 600phx;

    callback search(string);
    in property <[string]> elements;
    in property <string> preview;

    VerticalLayout {
        Rectangle {
            height: 3rem;
            TextInput {
                // single-line: false;
                // wrap: word-wrap;
                accepted => {
                    search(self.text);
                }
            }

            border-color: black;
            border-width: 0.05rem;

            background: gray;
            width: 100%;
        }

        HorizontalLayout {
            Rectangle {
                ScrollView {
                    VerticalLayout {
                        alignment: start;
                        // spacing: 0.5rem;
                        for e in elements: Text {
                            text: e;
                        }
                    }
                }

                border-color: black;
                border-width: 0.05rem;
                width: 50%;
                background: gray;
            }

            Rectangle {
                border-width: 0.05rem;
                border-color: black;
                background: gray;
                height: 100%;
                width: 50%;
                Text {
                    text: preview;
                }
            }

            height: 100%;
        }
    }
}
